In [2]:
##  Write the matrix multiplication
import numpy as np

def matrix_multiplication(Mtrx1,Mtrx2):
       
    Mtrx1_row=len(Mtrx1)
    Mtrx1_col=len(Mtrx1[0])
    
    
    Mtrx2_row=len(Mtrx2)
    Mtrx2_col=len(Mtrx2[0])
    
    print(f'first Mtrix No of Rows = {Mtrx1_row},first Matrix No of column = {Mtrx1_col},Second Mtrix Rows = {Mtrx2_row},Second Mtrix Cols = {Mtrx2_col}')
    
    Mtrx3=np.zeros((Mtrx1_row,Mtrx1_col),dtype=np.int16)
    #print(Mtrx3)
    
    if Mtrx1_col==Mtrx2_row:
        for i in range(Mtrx1_row):
            for j in range (Mtrx1_col):
                #Mtrx3[i][j]=0
                for k in range (Mtrx1_col):
                    Mtrx3[i][j]=Mtrx3[i][j]+Mtrx1[i][k]*Mtrx2[k][j]
                #print(Mtrx3[i][j]) for QC purpose   

        print(Mtrx3)
    else:
        print('Error: Number of col in first matrix should be equal to number of rows of second matrix')
              
    

In [6]:
def add_digit_decimals(num_str1, num_str2): #"2.3", "4.56" -> "6.86"
    result1=[]
    part2=[]
    result2=[]
    i=0
    while num_str1[i]!='.':
        i+=1
        
    part1=num_str1[:i]
    part2=num_str1[i+1:]
    #print(part1,part2)
    
    i=0
    while num_str2[i]!='.':
        i+=1
        
    part3=num_str2[:i]
    part4=num_str2[i+1:]
    #print(part1,part2,part3,part4)
    lst1=list(part2)
    lst2=list(part4)
    
   
    
    if len(lst2)>len(lst1):
        for i in range(len(lst1),len(lst2)):
            lst1.append('0')
    i = len(lst1) - 1
    j = len(lst2) - 1
    result = []
    carryover = 0
    r=0
    while i > -1 or j > -1:
        if i >= 0:
            n1 = int(lst1[i])
        else:
            n1 = 0
        
        if j >= 0:
            n2 = int(lst2[j])
        else:
            n2 = 0
        r = n1 + n2 + carryover
#         print(f"{n1} + {n2} -> {r}")
        result.append(r%10)
        carryover = r // 10
        i -= 1
        j -= 1
    
    number= int(part1)+int(part3)
    if carryover > 0:
        number+=carryover
    result.reverse()
    dec=''
    for i in result:
        dec+=str(i)
    print(number,'.',dec)   
          

In [4]:
# Write your own add digit arrays
#[1,1,2] + [1,2,1] -> [2, 3,3]
#[1,2] + [1,0] -> [2,2]

def add_digit(num_str1, num_str2):
    result=[]
    if len(num_str1)==len(num_str2):
        
        for i in range(len(num_str1)):
            result.append(num_str1[i]+num_str2[i])
        return (result)
    else:
        print("Error: length should be same for both array")

In [7]:
add_digit_decimals("2.3", "4.56")
add_digit_decimals("47.32", "4.56")
add_digit_decimals("47.32", "4.76")

6 . 86
51 . 88
52 . 08


In [8]:
Mtrx1=[[1,2,1],[3,1,7],[2,3,9]]
Mtrx2=[[2,1,3],[1,2,2],[1,1,2]]

matrix_multiplication(Mtrx1,Mtrx2)

first Mtrix No of Rows = 3,first Matrix No of column = 3,Second Mtrix Rows = 3,Second Mtrix Cols = 3
[[ 5  6  9]
 [14 12 25]
 [16 17 30]]


In [10]:
# Problem1:
# 2y = 40 -> [2, 40]
# y = 40/2 -> [20]

def solve1(arr):
    
    tmp=arr[1]/arr[0]
    return (tmp)

# Input: [3, 15]
# Expected: [5]

In [15]:
y=solve1([6,12])



In [12]:
# Problem 2

#2x + 5y = 78, y=2
#x = (78 - 5*2)/2

def solve_substitute(eqn, prev_ans):
    lst=[]
    L=len(prev_ans)
    eqlen=len(eqn)
    x=0
    
    for i in range(L):
        x=x+prev_ans[i]*eqn[i+1]
        #print('Multy value',x)
    
    x=(eqn[eqlen-1]-x)/eqn[0]
    
    lst.append(x)
    lst.append(prev_ans)
    return lst

#Example 1:
#solve_substitute([2, 5, 78], [2])
#expected_answer: [34, 2]

#Example 2:
# 3x + 5y - 10z = 30
# y, z = [1, 2]
# 3*x + 5*1 - 10*2 = 30
# x = (30 - (5*1 - 10*2))/3

#solve_substitute([3, 5, -10, 30], [1, 2]), 
#Expected_answer: [15, 1, 2]

In [14]:
solve_substitute([3, 5, -10, 30], [1, 2])

[15.0, [1, 2]]

In [17]:
# Problem 3
##A. 2x + 3y = 10
##B. 4x - 5y = 50


##Multiplier = 4/2
##C. B - 2*A
##C. -11y = 30
def find_multiplier(Marr,Mlen):
    
    mul=[]
    for i in range(1,Mlen):
        if Marr[0][0]>Marr[i][0]:
            mul.append(Marr[0][0]/Marr[i][0])
        else:
            mul.append(Marr[i][0]/Marr[0][0])
    
    return mul   

def reduce(arr):
    L= len(arr)
    k=0
    result = []
    
    #for i in range(0,L-2):
   
    #print(result)
    new_eqns =[]
    for i in range(1,L):
        res=[]
        result=find_multiplier(arr,L)
        
        for j in range(1,L+1):
            x=arr[i][j]-arr[0][j]*result[k]
            
            res.append(x)
        new_eqns.append(res)
            
        k+=1 
       
    return new_eqns

#input = [[2, 3, 10],
#    [4, -5, 50]]
#'''result = reduce(input)
#result = [-11, 30]

#result = reduce([
#    [1, 2, 3, 4], #x + 2y + 3z = 4
#   [2, 2, 4, 10],
#    [3, 4, 2, 30],
#])
#result: [
#    [ -2, -2, 2], #eqn2 - 2*eqn1
#    [-2, -7, 18],  #eqn3 - 2*eqn1
#]'''


In [18]:
reduce([[1, 2, 3, 4],[2, 2, 4, 10],[3, 4, 2, 30]])

[[-2.0, -2.0, 2.0], [-2.0, -7.0, 18.0]]

In [19]:
# Code convert to number a decimal numbers
# Problem 4: 
num = "१३७.७"
def convert(num):
    dic_numbers={'०':0,'१':1,'२':2,'३':3,'४':4,'५':5,'६':6,'७':7,'८':8,'९':9,'.':'.'}
    # print(137.7)
    for i in range(len(num)):
        for j,k in dic_numbers.items():
                   if num[i]==j:
                       print(k,end="")
                   

In [20]:
convert("१३७.७")

137.7

In [21]:
#Use XOR to swap without using third variable
x=70
y=800
x=x^y
y=x & (x^y)
x=x^y
print(x,y)

800 70
